Vipa\ExportBundle\Entity\DataExport:
    type: entity
    table: data_export
    repositoryClass: Vipa\ExportBundle\Entity\DataExportRepository
    cache:
        usage: NONSTRICT_READ_WRITE
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
          journal:
                targetEntity: Vipa\JournalBundle\Entity\Journal
                joinColumn:
                  name: journal_id
                  referencedColumnName: id
    fields:
        path:
            type: text
            nullable: true
        type:
            type: text
            nullable: true
        createdAt:
            type: datetime
            nullable: true