vipa_data_export_article:
  path:     /
  defaults: { _controller: "VipaExportBundle:ArticleExport:index" }

vipa_data_export_single_article_json:
  path:     /{id}/json
  defaults: { _controller: "VipaExportBundle:ArticleExport:singleArticleJson" }

vipa_data_export_single_article_xml:
  path:     /{id}/xml
  defaults: { _controller: "VipaExportBundle:ArticleExport:singleArticleXml" }

vipa_data_export_single_article_crossref:
  path:     /{id}/crossref
  defaults: { _controller: "VipaExportBundle:ArticleExport:singleArticleCrossref" }

vipa_data_export_single_article_pubmed:
  path:     /{id}/pubmed
  defaults: { _controller: "VipaExportBundle:ArticleExport:singleArticlePubmed" }
