vipa_data_export_issue:
  path:     /
  defaults: { _controller: "VipaExportBundle:IssueExport:index" }

vipa_data_export_single_issue_json:
  path:     /{id}/json
  defaults: { _controller: "VipaExportBundle:IssueExport:singleIssueJson" }

vipa_data_export_single_issue_xml:
  path:     /{id}/xml
  defaults: { _controller: "VipaExportBundle:IssueExport:singleIssueXml" }
