vipa_data_export_journal:
  path:     /
  defaults: { _controller: "VipaExportBundle:JournalExport:index" }

vipa_data_export_journal_json:
    path:     /json
    defaults: { _controller: "VipaExportBundle:JournalExport:json" }

vipa_data_export_journal_xml:
    path:     /xml
    defaults: { _controller: "VipaExportBundle:JournalExport:xml" }

vipa_data_export_journal_doaj:
    path:     /doaj
    defaults: { _controller: "VipaExportBundle:JournalExport:doaj" }
