vipa_data_export_user:
  path:     /
  defaults: { _controller: "VipaExportBundle:UserExport:index" }

vipa_data_export_single_user_json:
  path:     /{id}/json
  defaults: { _controller: "VipaExportBundle:UserExport:singleUserJson" }

vipa_data_export_single_user_xml:
  path:     /{id}/xml
  defaults: { _controller: "VipaExportBundle:UserExport:singleUserXml" }
