vipa_data_export:
  path:     /journal/{journalId}/export
  defaults: { _controller: "VipaExportBundle:Export:index" }

vipa_data_export_download:
  path:     /journal/{journalId}/export/{id}/download
  defaults: { _controller: "VipaExportBundle:Export:download" }

vipa_data_export_article:
  resource: routing/Export/article.yml
  prefix:     /journal/{journalId}/export/article

vipa_data_export_issue:
  resource: routing/Export/issue.yml
  prefix:     /journal/{journalId}/export/issue

vipa_data_export_journal:
  resource: routing/Export/journal.yml
  prefix:     /journal/{journalId}/export/journal

vipa_data_export_user:
  resource: routing/Export/user.yml
  prefix:     /journal/{journalId}/export/user
